#!/usr/bin/env python
#
# Copyright (c) 2021, Djaodjin Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import argparse, logging, os, sys


LOGGER = logging.getLogger(__name__)


def main(args):
    #pylint:disable=too-many-locals
    parser = argparse.ArgumentParser(
        usage='%(prog)s [options] command\n\nVersion\n  %(prog)s version '
        + str(__version__))
    parser.add_argument('--version', action='version',
        version='%(prog)s ' + str(__version__))
    parser.add_argument('--quiet', action='store_true',
        dest='quiet', default=False,
        help='Quiet mode. Only write on stderr when there is an error')
    parser.add_argument('--last-run', action='store',
        dest='last_run', default=None,
        help='Store a map of {logname: last_date} to use when deciding'\
            ' to download a log or not')
    parser.add_argument('--location', action='store',
        dest='location', default=None,
        help='Location where log files are stored')
    parser.add_argument('--list-all', action='store_true',
        dest='list_all', default=False,
        help='List all files (by default it will exclude the current log)')
    parser.add_argument('--download', action='store_true',
        dest='download', default=False,
        help='Download the rotated log files (by default upload)')
    parser.add_argument('--logsuffix', action='store',
        dest='logsuffix', default=None,
        help='Suffix inserted in log filenames on upload')
    parser.add_argument('lognames', metavar='lognames', nargs='+',
        help="rotated log files to upload/download")

    options = parser.parse_args(args[1:])
    if len(options.lognames) < 1:
        sys.stderr.write("error: not enough arguments")
        parser.print_help()
        return 1

    if options.quiet:
        logging.basicConfig(level=logging.ERROR)
    else:
        logging.basicConfig(format='%(message)s', level=logging.INFO)

    lognames = options.lognames
    logsuffix = options.logsuffix
    s3_location = options.location
    parts = s3_location[5:].split('/')
    s3_bucket = parts[0]
    s3_prefix = '/'.join(parts[1:])
    to_s3 = not options.download
    if to_s3:
        LOGGER.info(
            "Upload rotated logs for %s to bucket '%s' under prefix '%s'\n"
            % (' '.join(lognames), s3_bucket, s3_prefix))
    else:
        LOGGER.info(
            "Download rotated logs for %s from bucket '%s' under prefix '%s'\n"
            % (' '.join(lognames), s3_bucket, s3_prefix))

    local_prefix = '.' if not to_s3 else None
    if to_s3:
        # Upload
        _, s3_update = list_updates(
            list_local(lognames, prefix=local_prefix,
                       list_all=options.list_all),
            list_s3(s3_bucket, lognames, prefix=s3_prefix),
            logsuffix=logsuffix, prefix=s3_prefix)
        for item in s3_update:
            filename = item['Key']
            upload_log(s3_location, filename, logsuffix=logsuffix)
    else:
        # Download
        if options.last_run and os.path.exists(options.last_run):
            last_run = LastRunCache(options.last_run)
        else:
            last_run = None
        download_updated_logs(lognames,
            local_prefix=local_prefix, logsuffix=logsuffix,
            bucket=s3_bucket, s3_prefix=s3_prefix,
            last_run=last_run, list_all=options.list_all,
            time_from_logsuffix=True)
        if last_run:
            last_run.save()
    return 0


if __name__ == '__main__':
    #pylint:disable=invalid-name
    bin_path = os.path.realpath(os.path.abspath(sys.argv[0]))
    if bin_path.endswith('bin/dcopylogs'):
        sys.path += [os.path.join(
            os.path.dirname(os.path.dirname(bin_path)), 'lib',
            'python%d.%d' % (sys.version_info[0], sys.version_info[1]),
            'site-packages')]
    from tero import __version__
    from tero.dcopylogs import (LastRunCache, list_updates, list_local,
        list_s3, download_updated_logs, upload_log)

    sys.exit(main(sys.argv))
